
# 使用 Spring 的多环境配置
spring:
  profiles:
    active: ygh

---

spring:
  config:
    activate:
      on-profile: ygh
  datasource:

    # 配置 MYSQL 数据库的 URL 账号密码
    url: jdbc:mysql://localhost:3306/sosd_project?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 222316
  mail:

    # 配置邮件发送者的账号、密码等信息
    host: smtp.qq.com
    username: 1293978818@qq.com
    password: nttkmkrnjwljfhfd
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
  
  data:
    redis:

      # redis 的配置信息，包括地址、端口、密码等
      host: 192.168.37.131
      port: 6379
      password: 222316
      database: 0

# 用于产生 JWT 的密钥
my:
  secret: Mashiro
  admin-email: 1293978818@qq.com
logging:
  level:
    '[com.sosd.filters]': INFO